"""Render MoUs and ROI reports to PDF, or say plainly that it did not happen.

The prototype's fallback wrote the plain-text body to ``out_path`` — a path
ending in ``.pdf`` — and returned that path. The repo therefore shipped text
files with a ``.pdf`` extension: unopenable, mis-typed, and evidence of nothing.

Here the extension always tells the truth:

* ``reportlab`` present -> ``artifacts/documents/<name>.pdf``, and the file is
  verified to begin with the ``%PDF-`` magic bytes before it is reported.
* ``reportlab`` absent (or it fails) -> ``<name>.txt`` and ``<name>.html``, with
  ``data["pdf_path"] = None`` and ``degraded=True``.

A caller that wants "a PDF exists" checks ``data["pdf_path"]``, and if it is
``None`` there is no PDF. There is no code path in this module that writes a
non-PDF byte sequence to a ``.pdf`` filename.
"""
from __future__ import annotations

import html as html_module
import re
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

from core.protocols import ToolResult

from .base import BaseTool, annotate, guarded, tool

__all__ = ["RenderPdfTool", "PDF_MAGIC", "build_mou_lines", "build_roi_lines"]

#: Every real PDF begins with this. Checked before a path is reported as a PDF.
PDF_MAGIC = b"%PDF-"

_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9._-]+")

#: Only these two artefacts are rendered. Anything else is a caller mistake that
#: would produce a document nobody knows how to verify.
_KINDS = ("mou", "roi")


def _safe_name(name: str) -> str:
    """Reduce a caller-supplied stem to a safe filename.

    ``out_name`` arrives from artefact ids and brand names, so ``../../`` and
    ``C:\\windows\\`` are realistic inputs. Anything outside ``[A-Za-z0-9._-]``
    becomes ``_``, and a name that is only dots cannot escape the directory.
    """
    cleaned = _SAFE_NAME_RE.sub("_", (name or "").strip())[:80].strip("._")
    return cleaned or "document"


def _as_mapping(data: Any) -> dict[str, Any]:
    """Accept a ``MoU``/``ROIReport``, a mapping, or a list of mappings.

    Callers hand over whatever they happen to be holding; the renderer needs a
    dict and should not care which schema it came from.
    """
    if isinstance(data, Mapping):
        return dict(data)
    dump = getattr(data, "model_dump", None)
    if callable(dump):
        try:
            dumped = dump(mode="json")
        except TypeError:
            dumped = dump()
        if isinstance(dumped, Mapping):
            return dict(dumped)
    if isinstance(data, (list, tuple)):
        merged: dict[str, Any] = {}
        for item in data:
            merged.update(_as_mapping(item))
        return merged
    return {"content": str(data)}


def _line_for(key: str, value: Any) -> str:
    """One ``label: value`` line, with lists rendered as readable items."""
    label = str(key).replace("_", " ")
    if isinstance(value, (list, tuple)):
        if not value:
            return f"{label}: (none recorded)"
        bullets = "\n".join(f"  - {v}" for v in value)
        return f"{label}:\n{bullets}"
    if isinstance(value, Mapping):
        return _line_for(label, list(value.items()))
    if isinstance(value, bool):
        return f"{label}: {'yes' if value else 'no'}"
    if isinstance(value, float):
        return f"{label}: {value:,.2f}"
    return f"{label}: {value}"


def _render_lines(fields: Mapping[str, Any], *, title: str,
                  subtitle: str = "") -> list[str]:
    """Flatten a mapping into printable lines, keeping a document-like order."""
    lines: list[str] = [title]
    if subtitle:
        lines.append(subtitle)
    lines.append("")
    priority = ["mou id", "report id", "event id", "brand", "tier", "amount inr",
                "status", "version", "created at", "computed at", "terms"]
    seen: set[str] = set()
    for wanted in priority:
        for key, value in fields.items():
            if str(key).replace("_", " ") == wanted and key not in seen:
                lines.append(_line_for(key, value))
                seen.add(key)
    for key, value in fields.items():
        if key not in seen:
            lines.append(_line_for(key, value))
            seen.add(key)
    lines.append("")
    lines.append("Generated by Paytriq. Every figure above carries the assumption")
    lines.append("it was derived from; nothing here is estimated silently.")
    return lines


def build_mou_lines(mou: Any) -> list[str]:
    """Printable lines for a ``MoU``."""
    fields = _as_mapping(mou)
    brand = fields.get("brand", "sponsor")
    return _render_lines(
        fields,
        title="Paytriq — Memorandum of Understanding",
        subtitle=f"{brand} x {fields.get('event_id', 'event')}",
    )


def build_roi_lines(report: Any) -> list[str]:
    """Printable lines for an ``ROIReport``, with every assumption listed."""
    fields = _as_mapping(report)
    lines = _render_lines(
        fields,
        title="Paytriq — Sponsorship ROI Report",
        subtitle=f"event {fields.get('event_id', 'unknown')}",
    )
    assumptions = fields.get("assumptions") or []
    if assumptions:
        lines.append("")
        lines.append("Assumptions")
        lines.extend(f"  - {a}" for a in assumptions)
    return lines


@tool("render_pdf",
      "Render a MoU or ROI report to a real PDF under artifacts/documents. If "
      "reportlab is unavailable the output is written as honestly named .txt and "
      ".html with degraded=True and no .pdf path — plain text is never written "
      "to a file named .pdf.",
      mode="live", backend="reportlab")
class RenderPdfTool(BaseTool):
    """Produce a document a human can open, or an honest absence.

    ``data["pdf_path"]`` is the only field that means "a PDF exists". It is
    ``None`` whenever the renderer was unavailable or failed, and in that case
    ``result.degraded`` is ``True`` and ``result.reason`` says why.
    """

    def current_mode(self) -> str:
        #: Never "live": rendering is a local library call with no backend, no
        #: network and no credentials. Saying "live" here would overstate it in
        #: the same way the old tool overstated its PDF output.
        return "local-render" if _reportlab_available() else "degraded"

    def available(self) -> tuple[bool, str]:
        if not self.settings.tools_enabled:
            return False, "tools are disabled (settings.tools_enabled=False)"
        if _reportlab_available():
            return True, "reportlab installed: real PDF output"
        return True, ("reportlab NOT installed: will write .txt and .html and "
                      "report degraded=True. No PDF will be claimed.")

    # ------------------------------------------------------------------- public
    def run(self, kind: str = "mou", data: Any = None, *,
            out_name: str | None = None,
            title: str | None = None) -> ToolResult:
        """Render ``data`` as ``kind``.

        :param kind: ``"mou"`` or ``"roi"``.
        :param out_name: filename stem; sanitised. Defaults to the artefact id.
        """
        document_kind = (kind or "").strip().lower()
        if document_kind not in _KINDS:
            return ToolResult.failed(
                reason=(f"{self.name}: unknown document kind {kind!r}; expected "
                        f"one of {_KINDS}"),
                source=f"{self.name}:input")
        if data is None:
            return ToolResult.failed(reason=f"{self.name}: no document data given",
                                     source=f"{self.name}:input")

        fields = _as_mapping(data)
        if not fields:
            return ToolResult.failed(
                reason=(f"{self.name}: document data produced no printable "
                        f"fields; refusing to write an empty artefact"),
                source=f"{self.name}:input")

        lines = (build_mou_lines(fields) if document_kind == "mou"
                 else build_roi_lines(fields))
        stem = _safe_name(out_name or str(fields.get("mou_id")
                                          or fields.get("report_id")
                                          or f"{document_kind}_document"))
        # Callers (e.g. agents/a4_contract.py) pass ``"<id>.pdf"`` while this
        # tool appends ``.pdf`` itself; strip one trailing ``.pdf``
        # (case-insensitive) so ``mou_abc123.pdf`` -> ``mou_abc123.pdf`` on
        # disk instead of ``mou_abc123.pdf.pdf``. Bare stems are unchanged.
        if stem.lower().endswith(".pdf"):
            stem = stem[:-4].strip("._") or "document"
        directory = Path(self.settings.artifacts_dir) / "documents"
        pdf_path = directory / f"{stem}.pdf"

        if not _reportlab_available():
            return self._write_text_fallback(directory, stem, lines, title,
                                             reason=("reportlab is not installed, "
                                                     "so no PDF was produced"))
        return self._write_pdf(directory, stem, lines, pdf_path, title)

    # ------------------------------------------------------------------- pdf
    def _write_pdf(self, directory: Path, stem: str, lines: Sequence[str],
                   pdf_path: Path, title: str | None) -> ToolResult:
        """Build the PDF, then verify the bytes before claiming a PDF exists."""
        call = guarded(self._render, timeout=self.timeout, tool_name=self.name,
                       secrets=self.secrets, errors=_reportlab_errors())
        result = call(pdf_path, list(lines), title or "Paytriq")
        if not result.ok:
            # reportlab raised: fall back to honest text rather than propagate,
            # and say in the reason that the renderer failed (not just absent).
            return self._write_text_fallback(
                directory, stem, lines, title,
                reason=f"reportlab failed ({result.reason}); no PDF was produced")
        written: Path = result.data

        try:
            with written.open("rb") as handle:
                head = handle.read(len(PDF_MAGIC))
            size = written.stat().st_size
        except OSError as exc:
            return self._write_text_fallback(
                directory, stem, lines, title,
                reason=(f"rendered file could not be re-opened for verification "
                        f"({type(exc).__name__}: {exc}); no PDF is claimed"))
        if head != PDF_MAGIC:
            # Belt and braces: if the bytes are not a PDF, the .pdf file is a lie
            # and must not survive. Remove it and fall back to named text.
            try:
                written.unlink()
            except OSError:
                pass
            return self._write_text_fallback(
                directory, stem, lines, title,
                reason=(f"reportlab wrote a file that does not start with "
                        f"{PDF_MAGIC.decode()!r}; it was deleted rather than "
                        f"shipped as a PDF, and the content was written as .txt"))

        return ToolResult.success(
            {"pdf_path": str(written), "path": str(written),
             "format": "pdf", "lines": len(lines), "stem": stem,
             "bytes": size},
            source=f"{self.name}:reportlab")

    def _render(self, out_path: Path, lines: list[str], title: str) -> Path:
        """Blocking reportlab render. Raises for :func:`guarded` to convert."""
        from reportlab.lib.enums import TA_LEFT
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

        out_path.parent.mkdir(parents=True, exist_ok=True)
        styles = getSampleStyleSheet()
        heading = ParagraphStyle("paytriqHeading", parent=styles["Title"],
                                 alignment=TA_LEFT, fontSize=16, leading=20,
                                 spaceAfter=6)
        body = ParagraphStyle("paytriqBody", parent=styles["BodyText"],
                              fontSize=10, leading=13, spaceAfter=4)
        story: list[Any] = [Paragraph(html_module.escape(title), heading),
                            Spacer(1, 4 * mm)]
        for line in lines[1:]:
            if not line.strip():
                story.append(Spacer(1, 3 * mm))
                continue
            story.append(Paragraph(html_module.escape(line).replace(" ", "&nbsp;"),
                                   body))
        document = SimpleDocTemplate(
            str(out_path), pagesize=A4,
            title=title, author="Paytriq", subject=title,
            leftMargin=18 * mm, rightMargin=18 * mm,
            topMargin=16 * mm, bottomMargin=16 * mm,
        )
        document.build(story)
        return out_path

    # --------------------------------------------------------------- fallback
    def _write_text_fallback(self, directory: Path, stem: str,
                             lines: Sequence[str], title: str | None,
                             *, reason: str) -> ToolResult:
        """Write ``.txt`` and ``.html`` — and never a ``.pdf``.

        The returned status stays ``OK`` (rendering the text *did* succeed) but
        ``degraded=True``, ``data["pdf_path"] is None``, and the reason says
        exactly why there is no PDF. A caller that only checks ``ok`` still
        cannot be misled, because the pdf path it would read is ``None``.
        """
        text_path = directory / f"{stem}.txt"
        html_path = directory / f"{stem}.html"
        body = "\n".join(lines)
        html_body = ("<html><head><meta charset='utf-8'><title>{t}</title></head>"
                     "<body><h1>{t}</h1><pre>{b}</pre>"
                     "<p><strong>NOT A PDF.</strong> {r}</p></body></html>").format(
                         t=html_module.escape(title or "Paytriq"),
                         b=html_module.escape(body),
                         r=html_module.escape(reason),
                     )
        try:
            directory.mkdir(parents=True, exist_ok=True)
            text_path.write_text(body, encoding="utf-8")
            html_path.write_text(html_body, encoding="utf-8")
        except OSError as exc:
            return ToolResult.failed(
                reason=(f"{self.name}: could not write the fallback document "
                        f"({type(exc).__name__}: {exc})"),
                source=f"{self.name}:fallback")

        return annotate(
            ToolResult.success(
                {"pdf_path": None, "path": str(text_path),
                 "text_path": str(text_path), "html_path": str(html_path),
                 "format": "txt", "stem": stem, "lines": len(lines),
                 "note": ("No PDF was produced. The extensions above are "
                          "accurate: this file is text, and it is not named "
                          ".pdf.")},
                source=f"{self.name}:fallback"),
            degraded=True,
            reason=f"{self.name}: PDF not produced — {reason}. Wrote "
                   f"{text_path.name} and {html_path.name} instead.",
        )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<RenderPdfTool mode={self.current_mode()!r}>"


# ------------------------------------------------------------------- internals
def _reportlab_module() -> Any | None:
    """Import reportlab lazily so the package stays an optional dependency."""
    try:
        import reportlab  # noqa: F401
    except (ImportError, ModuleNotFoundError):
        return None
    return reportlab


def _reportlab_available() -> bool:
    return _reportlab_module() is not None


def _reportlab_errors() -> tuple[type[BaseException], ...]:
    """reportlab's own exception types, resolved lazily.

    ``reportlab.pdfbase.pdfdoc.PDFError`` and friends are not importable without
    the package installed, so they are resolved at call time and handed to
    :func:`tools.base.guarded` as extra expected types.
    """
    if not _reportlab_available():
        return ()
    try:
        from reportlab.pdfbase.pdfdoc import PDFError
    except (ImportError, ModuleNotFoundError, AttributeError):
        return ()
    return (PDFError,)


def iter_lines(payload: Mapping[str, Any]) -> Iterable[str]:  # pragma: no cover
    """Iterate printable lines for a mapping (exposed for the demo script)."""
    return _render_lines(payload, title="Paytriq")
